// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTCyliZ39zdNIXNMjjT4TVYnUmPrq4j_c',
    appId: '1:482325413457:web:95bdd90c85914b5ff14270',
    messagingSenderId: '482325413457',
    projectId: 'glib-6bb62',
    authDomain: 'glib-6bb62.firebaseapp.com',
    storageBucket: 'glib-6bb62.appspot.com',
    measurementId: 'G-34EVNZJ411',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJqzHvZoxy6h_uZvn173RDxcxvZVri9Qk',
    appId: '1:482325413457:android:0fdb3e291c5f8c09f14270',
    messagingSenderId: '482325413457',
    projectId: 'glib-6bb62',
    storageBucket: 'glib-6bb62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Ld5lhaHpFEsvRKOu_AhmWTFTuOW0BMY',
    appId: '1:482325413457:ios:7dc1be4ce80d28b2f14270',
    messagingSenderId: '482325413457',
    projectId: 'glib-6bb62',
    storageBucket: 'glib-6bb62.appspot.com',
    iosBundleId: 'com.example.glibPracticas',
  );
}
